controller_manager:
  ros__parameters:
    update_rate: 20.0

    ur_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur_joint_trajectory_controller:
  ros__parameters:
    joints:
      - A motor
      - B motor
      - C motor
      - D motor
      - E motor
      - F motor
    command_interfaces:
      - position
    state_interfaces:
      - position
