
/**:
  ros__parameters:
    # controller_manager
    update_rate: 20
    ur_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    ur_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # ur_joint_trajectory_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - finger_1_joint_1
      - finger_2_joint_1
      - finger_middle_joint_1
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: True
