controller_manager:
  ros__parameters:
    update_rate: 50
  
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joints:
      - gripper_finger_joint::right
      - gripper_finger_joint::left
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      gripper_finger_joint::right:
        goal: 0.02
      gripper_finger_joint::left:
        goal: 0.02

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0
    extra_joints: 
      - CASTER_WHEEL_FRONT_LEFT_JOINT
      - CASTER_WHEEL_FRONT_RIGHT_JOINT
      - CASTER_WHEEL_BACK_LEFT_JOINT
      - CASTER_WHEEL_BACK_RIGHT_JOINT
      - SMALL_WHEEL_JOINT
      - SMALL_WHEEL_JOINT_0
      - SMALL_WHEEL_JOINT_1
      - SMALL_WHEEL_JOINT_2
