controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    # Values don't correspond exactly to the ones in the robot URDF but result in more accurate odometry
    wheel_separation: 0.44
    wheel_radius: 0.098

    use_stamped_vel: false
    base_frame_id: "base_link"

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - CASTER_WHEEL_FRONT_LEFT_JOINT
      - CASTER_WHEEL_FRONT_RIGHT_JOINT
      - CASTER_WHEEL_BACK_LEFT_JOINT
      - CASTER_WHEEL_BACK_RIGHT_JOINT
      - SMALL_WHEEL_JOINT
      - SMALL_WHEEL_JOINT_0
      - SMALL_WHEEL_JOINT_1
      - SMALL_WHEEL_JOINT_2
      - head_1_joint
      - head_2_joint
      - torso_lift_joint
