webots_driver:
  ros__parameters:
    left_encoder: wheel_left_joint_sensor
    left_joint: wheel_left_joint
    right_encoder: wheel_right_joint_sensor
    right_joint: wheel_right_joint
    robot_base_frame: base_link
    synchronization: false
    use_joint_state_publisher: true
    wheel_distance: 0.5
    wheel_radius: 0.12
