controller_manager:
  ros__parameters:
    update_rate: 50.0

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_controller:
      type: joint_state_controller/JointStateController

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left wheel motor"]
    right_wheel_names: ["right wheel motor"]

    wheel_separation: 0.51
    wheel_radius: 0.141

    publish_rate: 50.0
