name: Documentation

on:
  push:
    branches:
      - master

jobs:
  generate_references:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Generate documentation
        run: |
          # Install dependencies
          sudo apt-get install git python3-setuptools
          pip3 install wheel
          pip3 install sphinx-markdown-builder sphinx
          export PATH=${PATH}:${HOME}/.local/bin

          # Generate docs
          cd docs
          make markdown

          # Initialize Git
          NAME=$(curl https://api.github.com/users/${GITHUB_ACTOR} | jq -r .name)
          ID=$(curl https://api.github.com/users/${GITHUB_ACTOR} | jq -r .id)
          git config --global user.name "${NAME}"
          git config --global user.email "${ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git reset --hard
          git fetch

          # Clone GitHub Wiki
          git clone https://github.com/${GITHUB_REPOSITORY}.wiki.git webots_ros2_wiki
          [ -d 'webots_ros2_wiki/API' ] && rm -rf webots_ros2_wiki/API
          mkdir webots_ros2_wiki/API
          cp -r build/markdown/*  webots_ros2_wiki/API

          # Publish docs to GitHub Wiki
          cd webots_ros2_wiki
          if [ ! -z "$(git diff)" ]; then
            git add -A
            git commit -m "API docs updated"
            git push "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.wiki.git"
          fi
